import { combineReducers } from 'redux';
import backendAPI from '../api/backendAPI';

const FETCH_CAMPAIGNS_REQUEST = 'FETCH_CAMPAIGNS_REQUEST';
const FETCH_CAMPAIGNS_REQUEST_SUCCESS = 'FETCH_CAMPAIGNS_REQUEST_SUCCESS';
const FETCH_CAMPAIGNS_REQUEST_FAILURE = 'FETCH_CAMPAIGNS_REQUEST_FAILURE';
const SAVE_CAMPAIGN_REQUEST = 'SAVE_CAMPAIGN_REQUEST';
const SAVE_CAMPAIGN_REQUEST_SUCCESS = 'SAVE_CAMPAIGN_REQUEST_SUCCESS';
const SAVE_CAMPAIGN_REQUEST_FAILURE = 'SAVE_CAMPAIGN_REQUEST_FAILURE';
const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
const SAVE_USER_REQUEST_SUCCESS = 'SAVE_USER_REQUEST_SUCCESS';
const SAVE_USER_REQUEST_FAILURE = 'SAVE_USER_REQUEST_FAILURE';
